title: Tatiana Garijo Amorós
description: Mi Portfolio
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Configuración de colecciones
collections:
  skills:
    output: true
    permalink: /skills/:path/
  projects:
    output: true
    permalink: /projects/:path/

    # Variables personalizadas
social:
  github: tatgaramo
  linkedin: tatiana-garijo-19a288156
  email: garijoamorostatiana@gmail.com

# Plugins (necesarios para GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
